### PR TITLE
schema diagram

### PR DESCRIPTION
**Pull request by PowerLevel9000**
# schema diagram added
team @RitaDee @PowerLevel9000 
- [ ] schema diagram added 
- [ ] based on this 
image
a SQL file is created

# Happy coding
 
MonkeyLookTheOtherWayGIF

### CODE REVIEW

**Comment by TuyishimireEric** [comment]
# INVALID ❌ ❌ ❌
### Hi @PowerLevel9000 👋

While you made a great effort in this project, I can't go ahead and review your code.

## Invalid Code Review Request ❌
Please, this is a **pair-programming project** 😨, Kindly make sure that everyone from your team has contributed equally to the project and submit again once you are done 🙏  

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Kindly create  a new PR that follows the Gitflow approach

Cheers and Happy coding!👏👏👏

✅ Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

⚠️ Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.

---
_Invalid Code Review Request does not count into the code reviews limit._

**Comment by PowerLevel9000** [comment]
@TuyishimireEric  
hi sir we did in pair programming but as we suppose to add only a Diagram I guess  so it is supposed to be done by one commit I guess

guide me if I made mistake somewhere

**Comment by AshakaE** [comment]
### Hi @PowerLevel9000  🙋 , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

# Invalid Code Review Request ❌ 

You have submitted a project, that has no commit history from other team members. Please be advised that while you may have worked together on this milestone, it is important that all team members have a commit history on the project

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Review by AshakaE — APPROVED** [review]
Hi @PowerLevel9000  & @RitaDee , 

### Highlights ✨ 

- Thanks for making the changes 👍 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Proceed to the next level 👏 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by PowerLevel9000** [comment]
hi @AshakaE ,

Thank you so much for taking the time to review my code on GitHub. Your feedback and suggestions have been incredibly valuable to me, and I appreciate your insights and expertise in this area.

**Pull request merged**
